# Alacritty Configuration
import = [
    #   "~/.config/alacritty/catppuccin-latte.toml" # obtained from https://github.com/catppuccin/alacritty
    #   "~/.config/alacritty/pz-dark.toml"
]

# Keybindings
[[keyboard.bindings]]
key = "V"
mods = "Alt"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Alt"
action = "Copy"

# Terminal bell
#[bell]
#audible = false

# Font settings
[font]
normal = { family = "Hack Nerd Font Mono"}
size = 18.0

# Scrolling
[scrolling]
history = 10000  # Use a large number to simulate "scrollback-unlimited"
multiplier = 3

# Cursor settings
[cursor]
style = "Block"
blink_interval = 0

