--require("nvim-treesitter").setup( {
--  -- A list of parser names, or "all" (the five listed parsers should always be installed)
--ensure_installed = {
--    "html",
--    "javascript",
--    "typescript",
--    "tsx",
--    "css",
--    "json",
--    "lua",
--    "vim",
--    "vimdoc",
--    "query",
--    "c",
--    "python",
--    "verilog",
--    "latex",
--  },
--
--  -- Install parsers synchronously (only applied to `ensure_installed`)
--  sync_install = false,
--
--  -- Automatically install missing parsers when entering buffer
--  -- Recommendation: set to false if you don't have `tree-sitter` CLI installed locally
--  auto_install = true,
--
--
--  highlight = {
--    enable = true,
--
--  },
--  indent = {
--    enable = true,
--    disable = {"python", "c"}
--  },
--
--   additional_vim_regex_highlighting = false,
--})
